"""Generate docs/error_budget.md from validation_results/sensitivity_error_budget.json.

The JSON is produced by running ``rocket_sim.validation.sensitivity`` (see docs/error_budget.md for the recipe), so the
tables in the document can never drift from the recorded numbers.

Run:  python scripts/gen_error_budget.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rocket_sim.validation.sensitivity import sensitivity_markdown  # noqa: E402

INTRO = """# Sensitivity study and physics error budget

Generated by `scripts/gen_error_budget.py` from `validation_results/sensitivity_error_budget.json`. Regenerate the data with
`rocket_sim.validation.sensitivity.run_sensitivity` / `model_form_study` (apogee = geometric apogee AGL, 6-DOF, dt as in
each config, run stopped 0.5 s after apogee).

**Quantity note.** The sensitivities below are for *geometric* apogee. The validation compares *barometer-equivalent* apogee, for which an
air-temperature change has the opposite sign (a warmer atmosphere raises true height but lowers the pressure-altitude reading by
about 0.8 % per +4 K for Genesis). The temperature row and the combined figure are therefore indicative of geometric apogee only;
the Monte Carlo in [validation.md](validation.md) uses the compared quantity.

**Purpose.** Before blaming the physics for a flight-to-flight discrepancy one must know how much apogee moves when the
things nobody measured move. This document ranks them, then lists model-form choices separately.

## 1. First-order input sensitivities (central differences, one input at a time)

`d(apogee) per sigma` is the apogee change for a one-standard-deviation change of the input, using the priors in
`validation/sensitivity.py::DEFAULT_PARAMS` (the same scale of ignorance as the Monte Carlo of validation.md). Combined
uncertainty = quadrature sum (assumes independence and linearity; the non-linear Monte Carlo is in
[validation.md](validation.md) section 6).
"""

OUTRO = """
### Reading the tables

* **Drag-related inputs dominate** large vehicles: surface roughness, the overall drag level, fin thickness and protuberance
  drag together contribute more than motor impulse. Roughness (60 um default) and fin thickness (3 mm assumed) are
  *assumptions* for every flight in the registry.
* **Impulse and mass** dominate the smaller 20 kg-class K-motor vehicle (Bella Lui): a 3 % impulse error is 6 % in apogee.
* **Wind, temperature, pressure and launch angle** are second order for apogee (<= 1 % each) at these wind speeds, but wind
  is first order for *drift* and for weathercocking, which this table does not show.
* The airframe CG appears small because apogee depends on it only through stability; its importance is for control.
* The first-order combined uncertainty (6.5-8.5 %) is the same size as the observed flight-to-flight apogee errors
  (0.5-13 %), i.e. **the validation flights cannot discriminate model errors smaller than about 6-8 %.**

## 2. Model-form study (changing a MODEL choice, nominal inputs)

*Disclosure:* the Erebus 11 and Cavour columns re-simulate the two holdout flights with model variants. This is a sensitivity
analysis of the model, not a logged holdout evaluation, and no model change followed from it.

Apogee change relative to the nominal run of each reconstructed flight. These are not uncertainties of an input; they are how
much the answer depends on a modelling decision.

"""

OUTRO2 = """
### Reading the model-form table

* **Aero hierarchy**: replacing the component build-up by a flat Cd (the coast average of the same vehicle over M 0.2-0.8)
  changes apogee by < 1 % for six of seven flights and 2.6 % for Prometheus; the *enhanced* model is identical to the
  Barrowman build-up to <= 0.4 m on every flight, because none of these simulations has a significant fin-lift
  slope change (all < Mach 0.95) or large angles of attack. **The enhanced model's transonic and supersonic behaviour is
  therefore untested by flights**; it is verified only analytically (`tests/test_aero_v11.py`).
* **3-DOF vs 6-DOF**: < 0.5 % except NDRT (-3.3 %) and Prometheus (-0.7 %), the vehicles with the largest weathercocking
  losses.
* **Gravity model and time step**: negligible (<= 0.13 %; time step 0.001 s vs the run's dt changes apogee by <= 4 cm, the thrust-corner/event floor in physics.md).
* **Surface roughness x2** moves apogee by 1-5 %, comparable to the whole drag-model uncertainty.
* **Mass convention (casing counted twice vs once)**: -9.6 to -12.4 % - the single largest effect found. Any validation using
  RocketPy-style parameters must state which convention it assumes; this registry assumes the reported mass already
  includes the casing.

## 3. Small-rocket view (the unvalidated regime)

The 0.45 kg, 41 mm example vehicle has the largest relative first-order uncertainty (8.5 %), driven by fin thickness,
surface roughness and drag level - exactly the quantities least known for small model rockets, where the Reynolds number is
lower (partly laminar boundary layers) and fins are relatively thick. No validation data exist for this class
([validation.md](validation.md) section 7), so this number is a *computed sensitivity*, not an accuracy claim.

## 4. Physics error budget (what the model leaves out)

| source | status | size / evidence |
|---|---|---|
| Unmeasured inputs (wind, T, p, launch angle, mass, impulse) | not modelled as known | 3-7 % apogee (1 sigma, section 1 and the Monte Carlo) |
| Drag-level / roughness / protuberances | modelled by build-up, unvalidated absolute level | 3-4 % per sigma (section 1); a post hoc +-7 % band covers 6 of 7 flights |
| Mass-property convention | assumption, flight-specific | up to -12 % |
| Transonic/supersonic drag and fin lift | analytic models only, **no flight validation** | unknown; Erebus 11 burnout speed unexplained |
| Fin flutter, aeroelasticity, fin-can interference | not modelled | not quantified |
| Rail tip-off, rail-button friction | rail is a straight guide, no tip-off | small for high thrust-to-weight; larger for small rockets |
| Real motor variability (curve shape, ignition delay, nozzle erosion) | thrust scale only | +-3-10 % impulse tolerance |
| Rotating, oblate Earth (Coriolis, geoid) | flat non-rotating Earth with g(h) | ~0.1-0.5 % apogee at 4 km, larger for drift |
| Atmospheric turbulence structure | simple Gauss-Markov / profiles | not validated |
| Numerics (RK4, dt) | converged | <= 4 cm in apogee at dt = 0.01 s vs 0.001 s (thrust-corner / event floor, physics.md) |
| Sensor/estimator realism | generic specs | not validated on real data |

A claim such as "apogee predicted to 2 %" is **not supported** for any flight in the registry; the defensible statement is
"within roughly +-6 % (RMS) of eight... of seven flights with unmeasured inputs, consistent with the stated uncertainty".
"""


def main() -> None:
    data = json.loads(
        (ROOT / "validation_results" / "sensitivity_error_budget.json").read_text(encoding="utf-8")
    )
    out = [INTRO]
    for res in data["sensitivity"].values():
        out.append(sensitivity_markdown(res))
    out.append(OUTRO)
    cases: dict[str, dict[str, float]] = {}
    flights = list(data["model_form"])
    for f in flights:
        for c in data["model_form"][f]["cases"]:
            key = c["case"]
            if key.startswith("aero: simplified"):
                key = "aero: simplified (flat coast-average Cd)"
            elif key.startswith("mass convention"):
                key = "mass convention: casing added on top of the reported mass"
            cases.setdefault(key, {})[f] = c.get("delta_pct", float("nan"))
    head = "| case | " + " | ".join(f.replace("_sim", "") for f in flights) + " |"
    out.append(head)
    out.append("|---|" + "---|" * len(flights))
    for key, d in cases.items():
        cells = [f"{d[f]:+.2f} %" if f in d and d[f] == d[f] else "n/a" for f in flights]
        out.append(f"| {key} | " + " | ".join(cells) + " |")
    nom = " | ".join(f"{data['model_form'][f]['nominal_apogee_m']:.0f}" for f in flights)
    out.append(f"| *nominal apogee [m]* | {nom} |")
    out.append(OUTRO2.replace("of eight... of seven flights", "of the seven flights"))
    (ROOT / "docs" / "error_budget.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote docs/error_budget.md")


if __name__ == "__main__":
    main()
