"""Generate reference documentation that must never drift from the code:

    docs/schema.md   telemetry column schema (from rocket_sim.data.schema)
    docs/config_reference.md   every configuration key with type and default (from the dataclasses)

Run:  python scripts/gen_docs.py
"""

from __future__ import annotations

import dataclasses
import sys
import typing
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rocket_sim.config import schema as S  # noqa: E402
from rocket_sim.data.schema import schema_markdown  # noqa: E402
from rocket_sim.data.spec import BatchSpec  # noqa: E402


def _type_name(tp: typing.Any) -> str:
    name = str(tp).replace("typing.", "").replace("<class '", "").replace("'>", "")
    return name.replace("rocket_sim.config.schema.", "").replace("|", "\\|")


def _walk(cls: type, prefix: str, lines: list[str], seen: set[type]) -> None:
    hints = typing.get_type_hints(cls)
    lines.append(f"### `{prefix or cls.__name__}`")
    lines.append("")
    lines.append("| key | type | default |")
    lines.append("|---|---|---|")
    nested: list[tuple[str, type]] = []
    for f in dataclasses.fields(cls):
        tp = hints[f.name]
        if f.default is not dataclasses.MISSING:
            default = repr(f.default)
        elif f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
            val = f.default_factory()
            default = "(section)" if dataclasses.is_dataclass(val) else repr(val)
        else:
            default = "**required**"
        lines.append(f"| `{f.name}` | `{_type_name(tp)}` | {default} |")
        for cand in (tp, *typing.get_args(tp)):
            if isinstance(cand, type) and dataclasses.is_dataclass(cand) and cand not in seen:
                nested.append((f"{prefix}.{f.name}" if prefix else f.name, cand))
                seen.add(cand)
    lines.append("")
    for name, c in nested:
        _walk(c, name, lines, seen)


def main() -> None:
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "schema.md").write_text(schema_markdown(), encoding="utf-8")
    lines = [
        "# Configuration reference",
        "",
        "Generated by `scripts/gen_docs.py` from `rocket_sim/config/schema.py` -- do not edit by hand.",
        "Units are in the key names (`_m`, `_kg`, `_s`, `_ms` = m/s, `_pa`, `_k`, `_hz`, `_deg`). Unknown keys are errors.",
        "",
    ]
    _walk(S.SimConfig, "", lines, {S.SimConfig})
    lines += ["", "# Batch / dataset specification reference", ""]
    _walk(BatchSpec, "", lines, {BatchSpec})
    (ROOT / "docs" / "config_reference.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote docs/schema.md and docs/config_reference.md")


if __name__ == "__main__":
    main()
